name: Build module release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 设置为 0 以获取所有标签历史

      - name: Install 7z
        uses: edgarrc/action-7z@v1.0.5

      - name: Get current time
        run: |
          random_number=$((RANDOM % 100))
          timestamp_with_random="$(date +'%Y%m%d')${random_number}"
          echo "$timestamp_with_random" > current_time.txt

      - name: Get latest tag
        id: latest-tag
        run: |
            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "$LATEST_TAG" > latest_tag.txt

      - name: Make module.prop and prepare files
        run: |
            LATEST_TAG=$(cat latest_tag.txt)
            CURRENT_TIME=$(cat current_time.txt)
            . ./module_settings/config.sh
            echo "id=${action_id}" > module.prop
            echo "name=${action_name}" >> module.prop
            echo "version=${LATEST_TAG}" >> module.prop
            echo "versionCode=${CURRENT_TIME}" >> module.prop
            echo "author=${action_author}" >> module.prop
            echo "description=${action_description}" >> module.prop

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
      
      - name: Build for aarch64
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang \
          -O2 -Wall -Wextra -o filewatch-aarch64 bin/filewatch.c
      
      - name: Build for x86_64
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang \
          -O2 -Wall -Wextra -o filewatch-x86_64 bin/filewatch.c
      
      - name: Strip binaries
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip bin/filewatch-aarch64
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip bin/filewatch-x86_64
      
      - name: Remove c files
        run: |
          rm -f bin/filewatch.c
          
      - name: Compress files
        run: |
            LATEST_TAG=$(cat latest_tag.txt)
            . ./settings/settings.sh
            7z a -r -mx9 "${MODULE_NAME}_${LATEST_TAG}.zip" * -x!*.git* -x!*.zip -x!latest_tag.txt -x!current_time.txt

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip
